# Image used as the build agent by Jenkins

FROM ubuntu:lunar

ARG DEBIAN_FRONTEND=noninteractive

# install base requirements
RUN apt-get update && apt-get install -y \
    wget \
    make \
    rsync \
    software-properties-common \
    openssh-client \
    git \
    dotnet-sdk-7.0 \
    aspnetcore-runtime-7.0 \
    dotnet-runtime-7.0

# install ansible
RUN add-apt-repository --yes --update ppa:ansible/ansible && apt-get install -y ansible

