# Image used as the build agent by Jenkins

FROM ubuntu:23.10

ARG DEBIAN_FRONTEND=noninteractive

# install base requirements
RUN apt-get update && apt-get install -y \
    wget \
    make \
    rsync \
    software-properties-common \
    openssh-client \
    git \
    sudo \
    libxml2-utils \
    python3

# install ansible
RUN add-apt-repository --yes --update ppa:ansible/ansible && apt-get install -y ansible

# install dotnet
RUN apt-get -y install dotnet8
