---

# Build snap

- name: Build snap
  hosts: opalopc-snap-builder

  vars:
    local_linux_build: "{{ repo_root.stdout }}/build/linux/opalopc"
    remote_linux_build: "{{ remote_linux_build_folder }}/opalopc"
    remote_linux_build_folder: "{{ snap_build_folder }}/{{ build_folder_bin }}"
    build_folder_bin: "bin"
    snap_build_folder: opalopc-snap-build
    version: "2.0.2.0"
    channel: "latest/edge"

  tasks:

    - name: Get repo root path
      local_action:
        module: ansible.builtin.shell
        cmd: >
          git rev-parse --show-toplevel
      register: repo_root

    - name: Create directories for build
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ snap_build_folder }}"
        - "{{ remote_linux_build_folder }}"

    - name: Copy opalopc build over
      ansible.builtin.copy:
        src: "{{ local_linux_build }}"
        dest: "{{ remote_linux_build }}"
        mode: '0775'

    - name: Make opalopc executable
      ansible.builtin.shell:
        cmd: "chmod +x {{ remote_linux_build }}"

    - name: Build snap
      block:
    
        - name: Move snapcraft file to build directory
          ansible.builtin.template:
            src: snapcraft.yaml.j2
            dest: "{{ snap_build_folder }}/snapcraft.yaml"
        
        - name: Build snap
          ansible.builtin.shell:
            cmd: >
              snapcraft
            chdir: "{{ snap_build_folder }}"
        
        - name: Publish snap
          ansible.builtin.shell:
            cmd: "snapcraft upload --release={{ channel }} opalopc_{{ version }}_amd64.snap"
            chdir: "{{ snap_build_folder }}"
