---

# Get daily metrics
# runs, runs per platform, installations, ratings, reviews

- name: Daily metrics
  hosts: localhost
  gather_facts: false

  vars:
    output_file: "{{ repo_root.stdout }}/daily-metrics.txt"
    umami_script_path: "{{ repo_root.stdout }}/deploy/playbooks/files/get-umami-metrics.py"
    number_days: 1

  tasks:

    - name: Get repo root path
      local_action:
        module: ansible.builtin.shell
        cmd: >
          cd ../.. && pwd
      register: repo_root

    - name: Get umami stats for {{ number_days }} days
      local_action:
        module: ansible.builtin.shell
        cmd: >
          python3 {{ umami_script_path }} {{ number_days }}
      environment:
        UMAMI_USERNAME: "{{umami_username | mandatory}}"
        UMAMI_PASSWORD: "{{umami_password | mandatory}}"
      register: umami_stats

    - name: Write results to file
      local_action:
        module: ansible.builtin.template
        src: metrics.j2
        dest: "{{ output_file }}"

