---

# Build Docusaurus website, add VERSION.txt, and deploy to Cloudflare Pages

- name: Deploy OpalOPC Website
  hosts: localhost

  vars_prompt:
    - name: version
      prompt: Version for the VERSION.txt?
      private: false

  vars:
    docusaurus_root: "{{ repo_root.stdout }}/opalopc-docs"
    build_dir: "{{ docusaurus_root | mandatory }}/build"
    report_resources: "{{ repo_root.stdout }}/OpalOPC/report-resources"
    docusaurus_report_resources_root: "{{ docusaurus_root | mandatory }}/static/report-resources"
    docusaurus_report_resources: "{{ docusaurus_report_resources_root | mandatory }}/{{ version | mandatory }}"

  tasks:

    - name: Get repo root path
      ansible.builtin.shell:
        cmd: git rev-parse --show-toplevel
      register: repo_root

    - name: Verify build_dir does not exist
      ansible.builtin.file:
        path: "{{ build_dir | mandatory }}"
        state: absent

    - name: Add report resources
      ansible.builtin.copy:
        src: "{{ report_resources }}/"
        dest: "{{ docusaurus_report_resources | mandatory }}/"

    - name: Build
      ansible.builtin.command:
        chdir: "{{ docusaurus_root | mandatory }}"
        cmd: "npx docusaurus build"
        creates: "{{ build_dir | mandatory }}"

    - name: Add VERSION.txt
      ansible.builtin.copy:
        content: "{{ version | mandatory }}"
        dest: "{{ build_dir | mandatory }}/VERSION.txt"

    - name: Deploy
      ansible.builtin.command:
        cmd: "npx wrangler pages deploy build --branch=main" # put to production (apex domain)
        chdir: "{{ docusaurus_root | mandatory }}"
      register: deploy_result

    - name: Cleanup
      ansible.builtin.file:
        path: "{{ build_dir | mandatory }}"
        state: absent

    - name: Print deploy result
      ansible.builtin.debug:
        msg: "{{ deploy_result.stdout_lines | mandatory }}"
