---

# Transfer the local database to the remote host

- name: Deploy KnownVulnerabilityAPI database
  hosts: hermione
  gather_facts: false

  tasks:

    - name: Include vault secrets
      ansible.builtin.include_vars:
        file: vault.yaml

    - name: Include api vars
      ansible.builtin.include_vars:
        file: vars.yaml

    - name: Local tasks
      delegate_to: localhost
      block:

        - name: Get repo root path
          ansible.builtin.shell:
            cmd: git rev-parse --show-toplevel
          register: repo_root

    - name: Create a volume for the database
      docker_volume:
        name: "{{ docker_volume_name }}"

    - name: Copy database over
      become: true
      ansible.builtin.copy:
        src: "{{ db_path_on_controller }}"
        dest: "{{ db_path_on_agent }}"
        force: true

    - name: Test API call
      ansible.builtin.include_tasks: "tasks/test-knownulnerabilityapi-call.yaml"
