---

# Update the local SQLite database used by KnownVulnerabilityAPI
# Fetches newest CVE and CPE data and re-creates the database
# This will take a long time

- name: Update local KnownVulnerabilityAPI Database
  hosts: localhost
  gather_facts: false

  vars:
    nvd_json_data_feeds_dir: "/home/valtteri/development/opalopc_nvd-json-data-feeds"
    cpe_dictionary_path: "/tmp/official-cpe-dictionary_v2.3.xml.gz"
    database_path: "/tmp/db.sqlite3"
    database_path_in_repo: "{{ repo_root.stdout }}/KnownVulnerabilityAPI/db.sqlite3"

  tasks:

    - name: Get repo root path
      ansible.builtin.shell:
        cmd: git rev-parse --show-toplevel
      register: repo_root

    - name: Update nvd-json-data-feeds
      ansible.builtin.git:
        repo: 'https://github.com/fkie-cad/nvd-json-data-feeds.git'
        dest: "{{ nvd_json_data_feeds_dir }}"
        single_branch: true
        accept_newhostkey: true

    - name: Download latest CPE dictionary
      ansible.builtin.get_url:
        url: https://nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml.gz
        dest: "{{ cpe_dictionary_path }}"
    
    - name: Populate database
      ansible.builtin.shell:
        cmd: "carton exec perl index.pl {{ nvd_json_data_feeds_dir }} {{ cpe_dictionary_path }} {{ database_path }}"
        chdir: "{{ repo_root.stdout }}/KnownVulnerabilityAPI/database-scripts"

    - name: Move database to repo
      ansible.builtin.shell:
        cmd: "mv {{ database_path }} {{ database_path_in_repo }}"
